### ISSUE TITLE
the Chinese translate is terrible

### ISSUE THREAD

**Issue by ImLoadingUuU** [santydesignscr/MOFHY-Lite-Multi-Language#1]
<img width="458" alt="截圖 2021-10-30 下午8 58 05" src="https://user-images.githubusercontent.com/69704016/139533721-c5f4b8bf-44d2-4c18-9af9-5c8bd5a3f1a1.png">
<img width="467" alt="截圖 2021-10-30 下午8 58 47" src="https://user-images.githubusercontent.com/69704016/139533739-ae0fba3d-fb7c-4ead-a34d-26a1fc2ad7f1.png">
購票,車票 not means support area 
发生器 not means generator please change it to 生成器
企业社会责任代码 not means CSR Code 🥴

**Comment by santydesignscr** [comment]
Ok, I make this translation whith an automatic json translator, if you want to contribute to improve this translation please download create a pull request

**Comment by santydesignscr** [comment]
I don't know Chinese and then I couldn't correct the machine translation

**Comment by ImLoadingUuU** [comment]
> Ok, I make this translation whith an automatic json translator, if you want to contribute to improve this translation please download create a pull request

I don't know how to use pull request 🙃

**Comment by santydesignscr** [comment]
Sorry for my late reply, If you want you can edit the file and then send it to my email santiago@santydesigns.com, I will add the credits in the readme and a comment within the file, and upload it

**Comment by ImLoadingUuU** [comment]
{
    "lang": "中文",
    "lang_code": "ch",
    "503": "503",
    "503_title": "未经授权的访问",
    "503_description": "你正试图查看一个未经你的用户授权的页面。",
    "settings_title": "帐户设置",
    "return": "返回到",
    "your_name": "您的姓名",
    "your_email": "您的电子邮件",
    "your_phone": "您的电话号码",
    "your_address": "您的家庭地址",
    "new_pass": "新密码",
    "new_pass_place": "这里的新密码...",
    "old_pass": "以前的密码",
    "old_pass_place": "这里的旧密码...",
    "change_pass": "更改密码",
    "desactivation_error": "理由必须至少有8个字符的长度...",
    "desactivation_alert": "您的账户将在停用30天后被删除，所有数据将被完全删除（这一行动不能被撤销）。",
    "desactivation_reason": "停用的原因",
    "desactivation_reason_place": "停用的原因应该放在这里...",
    "desactivate": "停用账户",
    "forget_title": "忘记密码",
    "email_address": "电子邮件地址",
    "email_address_place": "这里的电子邮件地址...",
    "recover_pass": "恢复密码",
    "login_nav": "进入",
    "register": "注册",
    "accounts_count": "帐户",
    "ssl_count": "SSL",
    "ticket_count": "购票",
    "server_count": "2台服务器",
    "accounts_advice_title": "欢迎来到免费主机",
    "accounts_advice_text": "在这里，你可以创建免费的主机账户，在世界最快的服务器上免费创建无限的网站。",
    "ssl_advice_title": "有免费的SSL!",
    "ssl_advice_text": "现在已经启用了SSL生成，使你能够快速访问你的网站并增加安全保护。",
    "accounts_action": "开始",
    "ssl_action": "现在查看",
    "login_title": "登录",
    "login_email": "电子邮件地址",
    "login_email_place": "电子邮件地址...",
    "login_pass": "密码",
    "login_pass_place": "密码...",
    "remember": "记住我",
    "login": "登录",
    "recover_pass_nav": "恢复密码",
    "maintaince_title": "哎呀!",
    "maintaince_text": "对不起，该服务因维护而暂时关闭，将很快激活。 请在24小时后访问该网站。",
    "my_accounts_title": "我的账户",
    "new_account": "新账户",
    "id": "身份证",
    "username": "用户名称",
    "deploy_date": "创建日期",
    "status": "状况",
    "action": "行动",
    "inactive": "不活跃",
    "active": "活跃",
    "suspended": "已暂停",
    "manage": "管理",
    "noting_find": "没有发现",
    "account_limit_alert": "你已经接近你的账户上限，请升级到高级主机以获得更多的资源和磁盘空间。",
    "accounts_limit": "/50个免费账户",
    "myssl": "我的SSL",
    "order_id": "订单编号",
    "metod": "方法",
    "processing": "处理",
    "expired": "过期",
    "my_settings_title": "我的设置",
    "first_name": "名字",
    "last_name": "姓氏",
    "company": "公司名称",
    "country": "国家",
    "select_country": "选择你的国家",
    "city": "城市名称",
    "postal_code": "邮政编号",
    "update_porfile": "更新资料",
    "update_image": "刷新图像",
    "confirm_pass": "确认密码",
    "confirm_pass_place": "确认密码....",
    "pass_confirm_error": "密码不匹配",
    "subject": "主题",
    "departament": "部门",
    "departament_hosting": "托管问题",
    "departament_ssl": "SSL问题",
    "departament_tech": "技术问题",
    "departament_client": "客户问题",
    "open": "开放式",
    "support_reply": "支持回应",
    "client_reply": "客户的回应",
    "closed": "关闭",
    "new_account_title": "新账户",
    "subdomain_title": "子域",
    "custom_domain": "自己的域名",
    "custom_domain_alert": "你需要配置给定的名称服务器，以便在我们这里托管域名。",
    "serach_place": "在此搜索域名...",
    "subdomain_name": "子域名称",
    "hosting_package": "托管套餐",
    "domain": "领域",
    "domain_place": "该域名将在此显示...",
    "account_username": "用户名称",
    "account_username_place": "自身产生的",
    "account_pass": "密码",
    "account_pass_place": "输入你的密码...",
    "create_account": "创建一个账户",
    "newssl_title": "新的SSL",
    "ssl_domain": "领域",
    "ssl_domain_place": "在此输入域名...",
    "request_ssl": "要求SSL",
    "newticket_title": "新票",
    "ticket_subjet": "客服单主题",
    "ticket_subjet_place": "输入客服单的主题...",
    "select_departament": "选择部门",
    "ticket_departament": "票务部",
    "ticket_content": "客服单内容",
    "ticket_content_place": "输入客服单的内容...",
    "create_ticket": "创建客服单",
    "my_porfile_title": "我的资料",
    "ip_address": "IP地址",
    "device_type": "设备类型",
    "device_os": "设备操作系统",
    "web_browser": "网络浏览器",
    "recover_token": "恢复令牌",
    "recover_token_place": "在这里，恢复令牌...",
    "register_pass": "密码",
    "register_pass_place": "密码...",
    "register_buttom": "注册",
    "logged_as": "登记为。",
    "main_menu": "主菜单",
    "logout": "退出",
    "suspended_title": "对不起!",
    "suspended_subtitle": "被暂停的账户",
    "suspended_text": "您的账户因过度使用资源或滥用服务而被暂停，请联系服务管理员，了解账户暂停的原因。",
    "validation_text": "<b>注意：</b>你需要验证这个账户，以便使用我们的免费主机或ssl服务。一封带有验证码的电子邮件已经发送到您的邮箱（<?php echo '<samp>'.$ClientInfo['hosting_client_email'].'</samp>';?>）。",
    "validation_key": "验证码",
    "validate": "验证",
    "resend": "转发电子邮件",
    "viewaccount_title": "查看账户",
    "control_panel": "控制面板",
    "filemanager": "文件管理器",
    "account_settings_buttom": "编辑设置",
    "cpanel_domain": "cPanel域名",
    "server_ip": "服务器IP",
    "your_ip": "你的IP",
    "ftp_host": "FTP主机名称",
    "ftp_port": "FTP端口",
    "mysql_host": "MySQL主机名称",
    "mysql_port": "MySQL端口",
    "inactive_alert": "你的账户现在不活跃，你需要创建一个新的问题单来删除这个记录",
    "account_open_ticket": "新建客服单",
    "view_ssl_title": "查看SSL",
    "cancelled": "取消了",
    "start_date": "开始日期",
    "finish_date": "结束日期",
    "private_key": "私钥",
    "csr_code": "CSR代码",
    "cname_record": "CNAME纪录",
    "record_content": "DNS纪录的内容",
    "ca_bundle": "CA 捆绑",
    "cert_code": "证书代码",
    "viewticket_title": "查看客服单",
    "date": "日期",
    "no_reply": "该客服单尚无回应",
    "cant_reply": "你不能再回答这个问题了，请开一个新的问题。",
    "new_reply_content": "回复的内容",
    "create_reply": "回复",
    "cplogin_title": "cPanel登录",
    "cplogin_text": "你现在被重新引导到控制面板。这可能需要5秒钟，这取决于你的网络速度。",
    "cplogin": "点击这里重定向",
    "dns_look": "DNS查询",
    "look_dns": "DNS查询",
    "decode_csr": "解码CSR",
    "decode": "解码",
    "know_title": "知识库",
    "subjet": "主题",
    "know_bases": "发现的知识库",
    "read": "阅读",
    "csr_gen": "CSR发生器",
    "csr_decoder": "CSR解码器",
    "request_csr": "申请CSR",
    "viewknow_title": "查看知识库",
    "content": "内容",
    "whois": "WHOIS",
    "look_whois": "WHOIS查询",
    "domains": "网域",
    "my_tools": "我的工具",
    "address": "地址",
    "your_state": "国家",
    "your_city": "城市"
}

**Comment by santydesignscr** [comment]
Wow, Thank you for your contribution, I will to add that to the code

**Comment by santydesignscr** [comment]
Added
