### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by OverdueWeevil2** [santydesignscr/MOFHY-Lite-Multi-Language#2]
Hello, can you add Turkish language support?

tr.json:

    {"lang":"Türkçe","lang_code":"tr","503":"503","503_title":"Yetkisiz Erişim","503_description":"Sizin için yetkisi olmayan sayfayı görüntülüyorsunuz.","settings_title":"Hesap Ayarları","return":"Geri","your_name":"Adınız","your_email":"E-Posta adresiniz","your_phone":"Telefon numaranız","your_address":"Evdeki adresiniz","new_pass":"Yeni Şifreniz","new_pass_place":"Yeni şifreniz buraya yazılacak ...","old_pass":"Mevcut Şifreniz","old_pass_place":"Mevcut Şifreniz buraya yazılacak ...","change_pass":"Şifreni Değiştir","desactivation_error":"Sebep en az 8 karakter uzunluğunda olmalıdır ...","desactivation_alert":"Hesabınız 30 gün boyunca askıya alındıysa sonsuza dek silinecektir! (Bu işlem geri alınamaz).","desactivation_reason":"Askıya alma sebebi","desactivation_reason_place":"Askıya alma sebebi buraya yazılacak ...","desactivate":"Hesabı askıya al","forget_title":"Şifremi unuttum","email_address":"E-Posta adresi","email_address_place":"E-Posta adresi buraya yazılacak ...","recover_pass":"Şifreyi kurtar","login_nav":"Giriş","register":"Kayıt","accounts_count":"Hesap","ssl_count":"SSL","ticket_count":"Bilet","server_count":"2 Sunucu","accounts_advice_title":"Ücretsiz Barındırmaya hoşgeldiniz!","accounts_advice_text":"Burada ücretsiz hosting hesapları oluşturabilir ve dünyanın en hızlı sunucularında sınırsız ücretsiz web siteleri oluşturabilirsiniz.","ssl_advice_title":"Ücretsiz SSL kullanılabilir!","ssl_advice_text":"Artık SSL Oluşturucunun web sitenize hızlı erişim sağlamasına ve güvenlik korumasını artırmasına izin veriyoruz.","accounts_action":"Başla(t)","ssl_action":"Şimdi gör","login_title":"Giriş yap","login_email":"E-Posta adresi","login_email_place":"E-Posta adresi ...","login_pass":"Şifre","login_pass_place":"Şifre ...","remember":"Beni hatırla","login":"Giriş yap","recover_pass_nav":"Parolayı kurtar","maintaince_title":"Üzgünüm!","maintaince_text":"Özür dileriz, hizmet bakım nedeniyle geçici olarak kapatılmıştır ve yakında etkinleştirilecektir, lütfen 24 saat sonra bu siteyi ziyaret edin.","my_accounts_title":"Hesaplarım","new_account":"Yeni Hesap","id":"ID","username":"Kullanıcı Adı","deploy_date":"Oluşturma tarihi","status":"Durum","action":"İşlem","inactive":"Aktif değil","active":"Aktif","suspended":"Askıya alındı","manage":"Yönet","noting_find":"Hiçbirşey Bulunamadı","account_limit_alert":"Hesap sınırınıza ulaşmaya yakın, lütfen daha fazla kaynak ve disk alanı için premium barındırmaya yükseltin.","accounts_limit":"/3 ücretsiz hesap","myssl":"SSL Sertifikalarım","order_id":"Sipariş numarası","metod":"Yöntem","processing":"İşleniyor","expired":"Süresi doldu","my_settings_title":"Ayarlarım","first_name":"Adı","last_name":"Soyadı","company":"Şirketin adı","country":"Ülke","select_country":"Ülkenizi seçin","city":"Şehirin adı","postal_code":"Posta Kodu","update_porfile":"Profili Güncelle","update_image":"Resmi Güncelle","confirm_pass":"Şifreyi Onayla","confirm_pass_place":"Şifreyi Onayla ...","pass_confirm_error":"Parolalar uyuşmuyor","subject":"Konu","departament":"Departman","departament_hosting":"Barındırma Sorunu","departament_ssl":"SSL Problemi","departament_tech":"Teknik Problem","departament_client":"Müşteri Sorunu","open":"Açık","support_reply":"Destek Yanıtı","client_reply":"Müşteri yanıtı","closed":"Kapalı","new_account_title":"Yeni Hesap","subdomain_title":"Alt Alan Adı","custom_domain":"Kendi Alan Adı","custom_domain_alert":"Alan adını bizde barındırabilmek için verilen sunucu adlarını yapılandırmanız gerekir.","serach_place":"Alan Adını Burada Ara ...","subdomain_name":"Alt Alan Adı","hosting_package":"Barındırma Paketi","domain":"Alan Adı","domain_place":"Alan adı burada görüntülenecek ...","account_username":"Kullanıcı Adı","account_username_place":"Otomatik oluşturur","account_pass":"Şifre","account_pass_place":"Şifreyi gir ...","create_account":"Hesabı Oluştur","newssl_title":"Yeni SSL","ssl_domain":"Alan Adı","ssl_domain_place":"Alan adınızı buraya yazın ...","request_ssl":"SSL İste","newticket_title":"Yeni Bilet","ticket_subjet":"Biletin Konusu","ticket_subjet_place":"Biletin konusunu girin ...","select_departament":"Departmanı Seçin","ticket_departament":"Bilet Departmanı","ticket_content":"Biletin içeriği","ticket_content_place":"Biletin içeriğini girin ...","create_ticket":"Bilet Oluştur","my_porfile_title":"Profilim","ip_address":"IP Adresi","device_type":"Cihaz türü","device_os":"Cihazın işletim sistemi","web_browser":"Web tarayıcı","recover_token":"Token Kurtarma","recover_token_place":"Token kurtarma buraya ...","register_pass":"Şifre","register_pass_place":"Şifre ...","register_buttom":"Kayıt Ol","logged_as":"Kayıtlı:","main_menu":"Ana menü","logout":"Çıkış","suspended_title":"Özür dilerim!","suspended_subtitle":"Hesap askıya alındı","suspended_text":"Kaynak kullanımı veya hizmetin kötüye kullanılması nedeniyle hesabınız askıya alındı, hesabın askıya alınma nedenini öğrenmek için lütfen hizmet yöneticisine başvurun.","validation_text":"<b>Not:<\/b> Ücretsiz barındırma veya ssl hizmetlerimizi kullanmak için bu hesabı doğrulamanız gerekir. Doğrulama anahtarıyla birlikte e-posta adresinize bir e-posta gönderildi. (<?php echo '<samp>'. $ClientInfo ['hosting_client_email']. '<\/samp>'; ?>)","validation_key":"Doğrulama Anahtarı","validate":"Doğrula","resend":"E-postayı ilet","viewaccount_title":"Hesabı görüntüleme","control_panel":"Kontrol Paneli","filemanager":"Dosya Yöneticisi","account_settings_buttom":"Ayarları Düzenle","cpanel_domain":"cPanel alan adı","server_ip":"Sunucu IP","your_ip":"IP Adresin","ftp_host":"FTP Sunucu Adı","ftp_port":"FTP Bağlantı Noktası","mysql_host":"MySQL Sunucu Adı","mysql_port":"MySQL Bağlantı noktası","inactive_alert":"Hesabınız artık etkin değil ve bu kaydı temizlemek için yeni bir bilet oluşturmanız gerekiyor!","account_open_ticket":"Bilet aç","view_ssl_title":"SSL Görüntüleniyor","cancelled":"İptal edildi","start_date":"Başlangıç tarihi","finish_date":"Bitiş tarihi","private_key":"Özel Anahtar","csr_code":"CSR Kodu","cname_record":"CNAME Kaydı","record_content":"Kaydın İçeriği","ca_bundle":"CA Bundle","cert_code":"Sertifika Kodu","viewticket_title":"Bilet görüntüleniyor","date":"Tarih","no_reply":"Bu bilete hala cevap yok","cant_reply":"Artık bu bilete cevap veremezsiniz, daha fazla soru için yeni bir bilet açın.","new_reply_content":"Yanıtın İçeriği","create_reply":"Yanıt Ekle","cplogin_title":"cPanel girişi","cplogin_text":"Şimdi panele yönlendiriliyor. İnternetinizin hızına bağlı olarak 5 saniye kadar sürebilir.","cplogin":"Yönlendirilmek için buraya tıklayın","dns_look":"DNS Araması","look_dns":"DNS araması","decode_csr":"CSR kodunu çöz","decode":"Çöz","know_title":"Bilgi Bankası","subjet":"Konu","know_bases":"bilgi tabanı bulundu","read":"Oku","csr_gen":"CSR Oluşturucu","csr_decoder":"CSR Kodu çöz","request_csr":"CSR iste","viewknow_title":"Bilgi tabanı görüntüleniyor","content":"İçerik","whois":"WHOIS Sorgula","look_whois":"WHOIS Sorgula","domains":"Alan adları","my_tools":"Araçlar","address":"Adres","your_state":"Eyalet","your_city":"Şehir"}

**Comment by santydesignscr** [comment]
Of course, if thank you very much for your contribution, I will add it right now.

**Comment by santydesignscr** [comment]
Added to the code, I will update the ready to install packages

**Comment by santydesignscr** [comment]
Ready
