### ISSUE TITLE
SSL Certificate does not work

### ISSUE THREAD

**Issue by greenreader9** [santydesignscr/MOFHY-Lite-Multi-Language#4]
I setup the API keys, fixed the missing ' (See pull request) but an error is still thrown when clicking "Request SSL". 

The error thrown in the "Something wemt' weong" one. Do you have the correct code for ```template/NewSSL.php``` and ```function/NewSSL.php``` that you can update the respiratory with?
Thanks!

**Comment by santydesignscr** [comment]
I will to see that

**Comment by santydesignscr** [comment]
It later of the update have an error 500

**Comment by greenreader9** [comment]
Thanks for looking into it!

**Comment by santydesignscr** [comment]
Please give me a momment bro

**Comment by santydesignscr** [comment]
Now is working, tanks for your contribution

**Comment by greenreader9** [comment]
No, it is still throwing an error, there is something else wrong besides the single quote.
