### ISSUE TITLE
[Solved] SSL Certificate Creation Error

### ISSUE THREAD

**Issue by greenreader9** [santydesignscr/MOFHY-Lite-Multi-Language#6]
Hello,
When creating an SSL certificate, an error message appears. Can you please check it out and implement a fix?
Thanks.

**Comment by santydesignscr** [comment]
All is working, see santyhost.ga/clientarea, you can try reinstalling

**Comment by santydesignscr** [comment]
![image](https://user-images.githubusercontent.com/88201812/142335570-4ab51003-8f20-4b61-b3e3-d83709b4c691.png)

**Comment by greenreader9** [comment]
Odd, is the GitHub code and the code you are using is the same? I updated the two relevant files and that did not fix it

**Comment by greenreader9** [comment]
Wait, did I need to add a database column?

**Comment by santydesignscr** [comment]
Yes, that is the problem

**Comment by santydesignscr** [comment]
I am using the same code

**Comment by greenreader9** [comment]
Ok, that seams to be working, but the SSL never moves out of the processing stage after the CNAME checks (And over 72 hours) have been completed. Have you managed to get a certificate?

**Comment by santydesignscr** [comment]
Yes I have some, I will to test now

**Comment by santydesignscr** [comment]
For the script side all is working, can be a GoGetSSL problem

**Comment by santydesignscr** [comment]
But I dont have wait the necesary time, may all is working normaly

**Comment by santydesignscr** [comment]
I have sucess verified my ssl

**Comment by santydesignscr** [comment]
Is not a problem of the script

**Comment by santydesignscr** [comment]
Make sure to delete your domain from the end, I mean if the record is _ABF4809B62653BDFC816989363B067B3.test.cf then add only _ABF4809B62653BDFC816989363B067B3

**Comment by santydesignscr** [comment]
![image](https://user-images.githubusercontent.com/88201812/142716195-e77b55fa-2fee-4f80-96ad-66d4be52501d.png)
![image](https://user-images.githubusercontent.com/88201812/142716199-3d3b72e8-e1d0-4f9c-9aeb-6be74916d436.png)
![image](https://user-images.githubusercontent.com/88201812/142716203-4662feb8-af2d-468e-be2d-a380ca5e93a1.png)

**Comment by santydesignscr** [comment]
![image](https://user-images.githubusercontent.com/88201812/142716286-ffdc9cd1-d09c-4a10-9c37-a7b363c1cf8c.png)

**Comment by santydesignscr** [comment]
Hello, its working for you or still having problems?

**Comment by greenreader9** [comment]
Hello, I'll check it out later today. Things that required my attention have come up, but I should be free later. Thanks for checking in!

**Comment by greenreader9** [comment]
I am also getting an error when creating a new certificate as well now. Are these the correct settings for the API?

![image](https://user-images.githubusercontent.com/75644395/143274467-ca1de3b8-fc29-4b84-8639-58bbcfa2f263.jpeg)

**Comment by greenreader9** [comment]
These settings seam to work, but are they correct? The certificate is stuck in pending mode (I know it has not been a long time, just want to be sure that everything else is correct). 

![image](https://user-images.githubusercontent.com/75644395/143275049-ce500322-c532-4987-8137-4fd668b38250.jpeg)

**Comment by greenreader9** [comment]
Looking a bit deeper, I found that the SSL vendor and the Client Area are telling me different things to add for the DNS check. 

GoGetSSL Reseller Dashboard
![image](https://user-images.githubusercontent.com/75644395/143277118-2e047710-3b3c-4f07-8191-1903fa2a6833.jpeg)

Client Area:
![image](https://user-images.githubusercontent.com/75644395/143277290-ddc45ed1-ed08-4512-b9ef-aa878a3292e9.jpeg)

Note the hi-lighted parts.

**Comment by greenreader9** [comment]
Ok, I got two certificates issued.

However, I get a CA bundle, and not a private key. I'm a missing something here?

![image](https://user-images.githubusercontent.com/75644395/143279134-0357a08b-809a-419c-9f43-c8b940114981.jpeg)

Thanks for your help thus far!

**Comment by santydesignscr** [comment]
Please make sure you have MOFHY Lite Multi Lang updated because that have to show the private key

**Comment by greenreader9** [comment]
It is working now, I forgot to update ```function/NewAccount.php```. I don't think it is safe to store the private key unencrypted in the database though. 

Thanks for your help!
