### ISSUE TITLE
After install not connecting with mofh

### ISSUE THREAD

**Issue by smacbca** [santydesignscr/MOFHY-Lite-Multi-Language#7]
i have installed in and added api and other setting as told in doc but it is not working, it is not showing clients and also not loading login page for user please tell help with

API Settings
- MOFH API Username (Added)
- MOFH API Password (Added)
- cPanel URL (Please tell which url to add here)
- Server IP  (Please tell which IP need to add here)
- Nameserver 1 / Nameserver 2  (can this need to change from ns1.byet.org and ns2.byet.org)
- Hosting Package (what to add here)

**Comment by santydesignscr** [comment]
That is a problem of the original code, I Will to fix that, and the clients only show if is active

**Comment by smacbca** [comment]
i have many actives clients but no one show, please tell me the info of what to add in following api settings

API Settings

MOFH API Username (Added)
MOFH API Password (Added)
cPanel URL (Please tell which url to add here)
Server IP (Please tell which IP need to add here)
Nameserver 1 / Nameserver 2 (can this need to change from ns1.byet.org and ns2.byet.org)
Hosting Package (what to add here)

**Comment by santydesignscr** [comment]
Login error fixed

**Comment by santydesignscr** [comment]
You are installing mofhy in a empty database?

**Comment by santydesignscr** [comment]
The existing MOFH clients will not imported

**Comment by santydesignscr** [comment]
In the clientarea only will to show the clients created with the clientarea clients

**Comment by santydesignscr** [comment]
In the hosting package you need to create a hosting package in the MOFH Panel and put the name there

**Comment by santydesignscr** [comment]
Please delete all of the files and Install aganin

**Comment by santydesignscr** [comment]
Again

**Comment by santydesignscr** [comment]
Please re donwload the zip file, beacuse i have maded some updates to fix a ssl error

**Comment by santydesignscr** [comment]
You can download from releades section, it is updated

**Comment by smacbca** [comment]
Ok...
And please tell me how to get GoGetSSL  SSL API Username  and password

**Comment by santydesignscr** [comment]
You have WhatsApp?

**Comment by santydesignscr** [comment]
I can help You to create You website

**Comment by smacbca** [comment]
i have done the setup of the panel and its working.

only one thing i don't know is that how to get GoGetSSL SSL API Username and password

Please tell instruction for how to get GoGetSSL SSL API Username and password

**Comment by santydesignscr** [comment]
I can send you a vídeo of how to create the goget ssl credentials

**Comment by santydesignscr** [comment]
I AM very Bad explaining

**Comment by santydesignscr** [comment]
I can send you a video

**Comment by smacbca** [comment]
i found that that you

**Comment by santydesignscr** [comment]
Ok
